spring:
  h2:

    console:
      enabled : true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sawaf
    password: sawaf
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl : true
    show-sql : true
    properties :
      hibernate :
        globally_quoted_identifiers : true
        format-sql : true
  sql :
    init :
      mode : never

  security :
    user:
      name : sawaf
      password: sawaf

